### ISSUE TITLE
缺少AddressablesAssetsHelper和AddressablesEditor两个类

### ISSUE THREAD

**Issue by JackMoljerc** [YMoonRiver/hybridclr_addressable#1]
如题

**Comment by YMoonRiver** [comment]
Assets/UnityGameFramework/GameFramework/Runtime/Resource/AddressablesAssetsHelper.cs
Assets/UnityGameFramework/GameFramework/Editor/AssetManagement/AddressablesEditor.cs
有这两个类，你需要宏定义 ADDRESSABLES_SUPPORT

**Comment by JackMoljerc** [comment]
![image](https://github.com/YMoonRiver/hybridclr_addressable/assets/31330808/496790ba-3147-4244-849a-ebc3e9f46995)
可以了 
![57F952BD](https://github.com/YMoonRiver/hybridclr_addressable/assets/31330808/18634557-7c5c-48b1-9d91-a815fc1d4331)


> Assets/UnityGameFramework/GameFramework/Runtime/Resource/AddressablesAssetsHelper.cs Assets/UnityGameFramework/GameFramework/Editor/AssetManagement/AddressablesEditor.cs 有这两个类，你需要宏定义 ADDRESSABLES_SUPPORT
